# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3760f275e504d25a2eaf7c0eb42696993d1a9d0dfc207592bf9250e955488702522e178fef5ff72a96540791a45bdd9e5f5cd199eb1ebc9c3b288eb9adf9f570

test:
  secret_key_base: 98f1e5836959f0b24683141cd68e649c1b6e6f2532023ddaa09bea0fb5c8cb01164ccd8e3c0af1748ebebde9878cb25d412d2347f67ddc7065aa9332c9a37b2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
